---

- name: Provision host server
  hosts: master
  user: root
  vars_files:
    - vars/external_vars.yml
    - vars/private_vars.yml

  roles:
    - role: ansible-ssh
    - role: ansible-utils
    - role: ansible-libvirt
    - role: ansible-pxe
      pxe_centos_repository: {{repository}}
      pxe_ssh_keys: ssh_keys
    - role: ansible-iptables
      iptables_accepted_intefaces:
        - virbr0
